### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by deklanw** [shermp/Kobo-UNCaGED#23]
```
Kobo-UNCaGED v0.3.0
Kobo Aura HD
Calibre 4.2
```

Just installed KFMon yesterday per these instructions https://www.mobileread.com/forums/showthread.php?t=314220 using this `Plato-0.7.7_KOReader-v2019.09.3.zip`

Getting this error:

```
failed to read metadata file: error reading metadata.calibre JSON: json: cannot unmarshal string into Go struct field KoboMetadata.application_id of type int
```

**Comment by shermp** [comment]
Umm... looks like there may be some Calibre 4 issues (I'm still running 3.48).

Am investigating with a portable Calibre 4 instance to see what broke...

**Comment by shermp** [comment]
Can you please connect your Kobo to your PC, find and open `metadata.calibre` in a text editor, and search for any instance of `"application_id":`, where the value following it is enclosed in quotes? If found, can you let me know what the value(s) are?

I have this horrible suspicion it will be something like "None"...

**Comment by deklanw** [comment]
@shermp 
Most of them are `null` but some of them seem to be proper. 

Yesterday when I installed KFMon etc it looked like the stock Kobo library picked up all the files in the Plato and KOReader folders like: "align-center.svg" from Plato, "appbar.align.auto.png" from KOReader etc.

It seems those are the ones which have `null` as their value.

**Comment by shermp** [comment]
Ah... I see the problem now. I assumed all items would have an `application_id`. Your explanation makes sense as to why that might not be the case.

Thankfully, that's an easy fix.

**Comment by NiLuJe** [comment]
@deklanw: See https://github.com/koreader/koreader/issues/5430 for the indexing "issue" ;).

**Comment by shermp** [comment]
Released v0.3.1, which hopefully fixes this. Please let me know if it doesn't.

**Comment by deklanw** [comment]
Works now! Thank you for your work.

**Comment by shermp** [comment]
> Works now! Thank you for your work.

You're welcome.
