### ISSUE TITLE
Error Message after ejecting

### ISSUE THREAD

**Issue by AllisterW** [shermp/Kobo-UNCaGED#31]
Thank you for this very useful package.

I am using a Forma on FW4.21.15015
Error came up on reinstall after factory reset.
Manual install of KFMon failed so I installed KFMon using one click KOReader package which bundles KFMon & NickelMenu (OCP-KOReader-v2020.06.zip)

After reboot unzipped KoboUncaged-v0.4.1-full.zip to drive root.
Connection to calibre seems ok.
Transfer of files and Nickel post processing of books seems ok.

But Calibre emitted the error message below after ejecting kobo.
No error message using cable.

BTW I just noticed that nickel processes books differently when using this package.
It slots books into author named directories with kobo forma driver.
Where as with the wireless device driver the books are all in the drive directory.
Is this the expected behavior?

==================

calibre, version 4.19.0
ERROR: Unhandled exception: <b>ControlError</b>:Device responded with incorrect information

calibre 4.19 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.16+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 32, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 32, 0) && KePub Input (3, 2, 10) && KindleUnpack - The Plugin (0, 82, 1) && Kindle Collections (1, 7, 26) && KePub Metadata Writer (3, 2, 12) && KoboTouchExtended (3, 2, 12) && KePub Metadata Reader (3, 2, 9) && KePub Output (3, 2, 12) && KFX metadata reader (from KFX Input) (1, 32, 0) && KFX Input (1, 32, 0)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 350, in umount_device
  File "site-packages\calibre\devices\smart_device_app\driver.py", line 50, in _synchronizer
  File "site-packages\calibre\devices\smart_device_app\driver.py", line 1459, in eject
  File "site-packages\calibre\devices\smart_device_app\driver.py", line 50, in _synchronizer
  File "site-packages\calibre\devices\smart_device_app\driver.py", line 643, in _call_client
  File "site-packages\calibre\devices\smart_device_app\driver.py", line 685, in _receive_from_client
ControlError: Device responded with incorrect information

**Comment by NiLuJe** [comment]
The save template (directory layout when sending books) is device-plugin specific.

It *might* even be device-specific? I don't recall exactly how that works with the Smart device device plugin, though, but looking at its settings might be a good start.

**Comment by shermp** [comment]
Calibre made some changes in the most recent versions, one of those regarding eject. I was hoping KU would still work fine with it, but it looks like I might need to look into this.

(The changes were made at the request of koreader, because for some reason they couldn't use the TCP disconnection as an eject indicator.)

**Comment by shermp** [comment]
@AllisterW As I thought, it was an issue with the new 'eject' notification from recent versions of Calibre. Was fixed in the upstream version of UNCaGED, and I've created a preview release [here](https://github.com/shermp/Kobo-UNCaGED/releases/tag/v0.4.2pre) for Kobo UNCaGED.

WARNING, I haven't actually tested the preview on a Kobo (It seems to work alright on my desktop). It should work though.

**Comment by AllisterW** [comment]
@shermp Wow, just wow.  This must be a passion project.  Fixed in less than a day!!! Thank you so much.

@NiLuJe: Am not a programmer myself.  But this is an incentive to learn programming, if I don't quite like how a piece of software behaves.

**Comment by shermp** [comment]
@AllisterW it was a quick fix, so didn't take much effort. I knew what changed in calibre, so I knew where to look in my own code, and the problem was pretty obvious.
