### ISSUE TITLE
Kobo Libra 2: no UI, and log says "failed to get kobo info: unknown device"

### ISSUE THREAD

**Issue by jucor** [shermp/Kobo-UNCaGED#43]
Dear @shermp 

Thanks for a very promising tool! I just bought a Kobo Libra 2, and sadly the UI is not showing. I get the message "Running precautionary library rescan", then just a window saying "Finished", and that's it.

I am using Kobo LIbra 2, Model N418, FCC ID: NOIKBN418, IC: 8857A-KBN418, with Firmware 4.21.19086 (2adb3f45ad, 1/20/22).
I am using Kobo-UNCaGED release 0.5.2.

I checked  [ku.log](https://github.com/shermp/Kobo-UNCaGED/files/8191127/ku.log) , attached. 

It looks like https://github.com/shermp/Kobo-UNCaGED/blob/46c23091e7dbd486012333299659377426a8ab1c/kobo-uncaged/device/device.go#L84 is failing and thus exiting.
How can I help? I was looking for a debug mode that would print the return of `kobo.DeviceByID` obtained in https://github.com/shermp/Kobo-UNCaGED/blob/46c23091e7dbd486012333299659377426a8ab1c/kobo-uncaged/device/device.go#L308, but no dice.

Happy to help debug this any way I can!

**Comment by jucor** [comment]
Ah, looks like the problem is in the kobo-utils package not yet knowing Libra 2: https://github.com/pgaskin/koboutils/issues/5

**Comment by jucor** [comment]
I've sent a pull request upstream https://github.com/pgaskin/koboutils/pull/7  -- any eyes on it are very welcome @shermp please :) since I'm new to Go and to Kobo.

**Comment by shermp** [comment]
Thank you for prodding me to do some updates. It's been a while...

I've finally got off my posterior and implemented a GH workflow to build KU. It helps that the fine Koreader folks decided to release binary koxtoolchain packages, which was a massive help.

(Untested) builds are now available from the `Actions` tab. Next job will be to update koboutils

**Comment by shermp** [comment]
@jucor Builds should now be available in the Actions tab that work on the Libra 2. Eg: https://github.com/shermp/Kobo-UNCaGED/suites/5549544789/artifacts/178880020

**Comment by jucor** [comment]
Woohoo, it works on the Libra 2 ! Thanks a lot for your reactivity and for the great tool :)

**Comment by shermp** [comment]
@jucor no worries.

I must admit, I've been ignoring KU for quite a while. I haven't really worked on any Kobo stuff for a few months (except for helping with the FW 4.31 patches).

I suppose I should make a new release sometime...

**Comment by jucor** [comment]
This is something you're doing on your free time, noone has any right to demand you maintain it like clockwork! A release would likely be helpful to buyers of new kobos, of course - I've found KU so easier than having to root around for the right cable :)
