### ISSUE TITLE
Support for Kobo Sage and Libra 2

### ISSUE THREAD

**Issue by MercuryGlitch** [shermp/Kobo-UNCaGED#44]
I posted on the MR forums, posting here as well just to cover all angles.  Running KU on a Sage or Libra 2 results in the following log being generated.  KU does not get to the point of checking for wifi or opening the browser to check for Calibre.

Apr 08 21:25:44 [Kobo-UNCaGED] Enabled loopback interface
Apr 08 21:25:44 [Kobo-UNCaGED] Starting Kobo UNCaGED
[Kobo-UNCaGED] 2022/04/08 21:25:44 Started Kobo-UNCaGED
[Kobo-UNCaGED] 2022/04/08 21:25:44 Creating KU object
[Kobo-UNCaGED] 2022/04/08 21:25:44 Getting Kobo Info
[Kobo-UNCaGED] 2022/04/08 21:25:44 New: failed to get kobo info: New: unknown device
[Kobo-UNCaGED] 2022/04/08 21:25:44 New: failed to get kobo info: New: unknown device
Apr 08 21:25:44 [Kobo-UNCaGED] Running precautionary library rescan
Apr 08 21:25:47 [Kobo-UNCaGED] Disabled loopback interface

**Comment by shermp** [comment]
This is the same issue as #43 

I've fixed this, but forgot to issue a new release, apologies for that. In the meantime, you can download the artifact from https://github.com/shermp/Kobo-UNCaGED/actions/runs/1940063067

**Comment by shermp** [comment]
New release now available at https://github.com/shermp/Kobo-UNCaGED/releases/tag/v0.5.5
