### ISSUE TITLE
Clara BW Problems

### ISSUE THREAD

**Issue by Foreeps** [shermp/Kobo-UNCaGED#53]
Hello,

I've been trying to use KU on my new Clara BW, and it's been giving me problems almost from the beginning, so I'm guessing it's because no one has tried it on a BW before.  (And I'm sure it doesn't help that the BW was released two years after the current KU version.)  NickelMenu installed fine.  Following the install instructions for KU caused it to attempt to install NickelDBus and reboot every time I tried to launch KU, over and over again.  I uninstalled KU, went to the NickelDBus homepage and installed it manually, which was successful.  I reinstalled KU, and it didn't try to install NickelDBus again; instead it pops up a dialog "Starting Kobo UNCaGED", then it says "Running precautionary library rescan" very briefly, then it has a message box titled "Kobo UNCaGED" that just says "Finished!" and has a "Continue" button.  Clicking on "Continue" closes the message box, and leaves me on the home screen.

I also haven't been able to enter developer mode: it actually just searches for "devmodeon" and no menus unlock, so I haven't gotten to any logs.  I wasn't able to find any BW-specific instructions, everyone is just giving the normal method.

Perusing the other issues, I saw "Clara 2E support? #51" and figured this was a similar thing with an old version of koboutils, since the BW didn't even exist when 0.5.5 was built.  (For what it's worth, the Calibre Kobo Utilities plugin seems to handle the BW fine, I don't know if that uses the same library or just has a similar name.  Probably unrelated, since none of the programmer names match.)

So I don't really know what I'm doing with Github - is there anything I can do to update the dependency and build a newer version?  Would that be enough?

Thank you!

**Comment by shermp** [comment]
Hi @Foreeps good news. I've tagged a new release, you can get it from https://github.com/shermp/Kobo-UNCaGED/releases/tag/v0.5.6

**Comment by Foreeps** [comment]
Thank you so much!

There are some quirks, like it will only run once and then requires a reboot, but I can work with that!
